main:
  steps: all
  experiment_name: robotathome_perception_pipeline
  project_name: robotathome_yolo_perception
  artifact_backend: dvc
  mlflow_version: 2.14.1
  dvc_remote: C:\Data\Repos\dvc\robotathome_yolo_perception
download:
  dataset_sources:
  - out_dir: 'C:\Users\fixc9dv\Downloads'
    extract_root: '..\..\data'
    force_download: false
    dataset_url: "https://zenodo.org/record/7811795/files/Robot@Home2_db.tgz"
    dataset_filename: "Robot@Home2_db.tgz"
    dataset_md5: "d34fb44c01f31c87be8ab14e5ecd0767"
    dataset_extract_to: "."
  - out_dir: 'C:\Users\fixc9dv\Downloads'
    extract_root: '..\..\data'
    force_download: false
    dataset_url: "https://zenodo.org/record/7811795/files/Robot@Home2_files.tgz"
    dataset_filename: "Robot@Home2_files.tgz"
    dataset_md5: "c55465536738ec3470c75e1671bab5f2"
    dataset_extract_to: "files"
annotation_convert:
  rh_path: '..\..\data'
  rgbd_path: '..\..\data\files\rgbd'
  scene_path: '..\..\data\files\scene'
  output_root: '..\..\data\yolo'
  epsilon_ratio: 0.002
  labels_root: '..\..\data\yolo\labels'
  mapping_json: '..\..\data\yolo\class_id_to_name.json'
  name_mode: ot
  force_convert: false
  backup: true
split:
  source_root: '..\..\data\yolo'
  output_root: '..\..\data\training'
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  seed: 42
  image_exts: .jpg,.jpeg,.png
  use_stratified: true
  rare_threshold: 20
training:
  dataset_root: '..\..\data\training'
  output_root: '..\..\data\results'
  mapping_json: '..\..\data\yolo\class_id_to_name.json'
  model_name: yolo11s-seg.pt
  run_name: robotathome_seg_strat
  epochs: 50
  imgsz: 640
  batch: -1
  device: 0
  workers: 10
inference:
  source: ''
  output_dir: ''
  model_path: '..\..\data\results\runs\robotathome_seg_strat\weights\best.pt'
  mapping_json: '..\..\data\yolo\class_id_to_name.json'
  conf_threshold: 0.70
  imgsz: 640
  device: 0
